//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_ASPNET.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitudes", Namespace="http://schemas.datacontract.org/2004/07/WCFExamen")]
    [System.SerializableAttribute()]
    public partial class Solicitudes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fsolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nsolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desact {
            get {
                return this.desactField;
            }
            set {
                if ((object.ReferenceEquals(this.desactField, value) != true)) {
                    this.desactField = value;
                    this.RaisePropertyChanged("desact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descat {
            get {
                return this.descatField;
            }
            set {
                if ((object.ReferenceEquals(this.descatField, value) != true)) {
                    this.descatField = value;
                    this.RaisePropertyChanged("descat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                if ((object.ReferenceEquals(this.dniField, value) != true)) {
                    this.dniField = value;
                    this.RaisePropertyChanged("dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fsolicitud {
            get {
                return this.fsolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.fsolicitudField, value) != true)) {
                    this.fsolicitudField = value;
                    this.RaisePropertyChanged("fsolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nsolicitud {
            get {
                return this.nsolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.nsolicitudField, value) != true)) {
                    this.nsolicitudField = value;
                    this.RaisePropertyChanged("nsolicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actividad", Namespace="http://schemas.datacontract.org/2004/07/WCFExamen")]
    [System.SerializableAttribute()]
    public partial class Actividad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idcategField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vacantesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desact {
            get {
                return this.desactField;
            }
            set {
                if ((object.ReferenceEquals(this.desactField, value) != true)) {
                    this.desactField = value;
                    this.RaisePropertyChanged("desact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idact {
            get {
                return this.idactField;
            }
            set {
                if ((object.ReferenceEquals(this.idactField, value) != true)) {
                    this.idactField = value;
                    this.RaisePropertyChanged("idact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcateg {
            get {
                return this.idcategField;
            }
            set {
                if ((object.ReferenceEquals(this.idcategField, value) != true)) {
                    this.idcategField = value;
                    this.RaisePropertyChanged("idcateg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vacantes {
            get {
                return this.vacantesField;
            }
            set {
                if ((object.ReferenceEquals(this.vacantesField, value) != true)) {
                    this.vacantesField = value;
                    this.RaisePropertyChanged("vacantes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/WCFExamen")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fsolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nsolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                if ((object.ReferenceEquals(this.dniField, value) != true)) {
                    this.dniField = value;
                    this.RaisePropertyChanged("dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fsolicitud {
            get {
                return this.fsolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.fsolicitudField, value) != true)) {
                    this.fsolicitudField = value;
                    this.RaisePropertyChanged("fsolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idact {
            get {
                return this.idactField;
            }
            set {
                if ((object.ReferenceEquals(this.idactField, value) != true)) {
                    this.idactField = value;
                    this.RaisePropertyChanged("idact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nsolicitud {
            get {
                return this.nsolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.nsolicitudField, value) != true)) {
                    this.nsolicitudField = value;
                    this.RaisePropertyChanged("nsolicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Solicitudes", ReplyAction="http://tempuri.org/IService1/SolicitudesResponse")]
        Examen_ASPNET.ServiceReference1.Solicitudes[] Solicitudes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Solicitudes", ReplyAction="http://tempuri.org/IService1/SolicitudesResponse")]
        System.Threading.Tasks.Task<Examen_ASPNET.ServiceReference1.Solicitudes[]> SolicitudesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Actividades", ReplyAction="http://tempuri.org/IService1/ActividadesResponse")]
        Examen_ASPNET.ServiceReference1.Actividad[] Actividades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Actividades", ReplyAction="http://tempuri.org/IService1/ActividadesResponse")]
        System.Threading.Tasks.Task<Examen_ASPNET.ServiceReference1.Actividad[]> ActividadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Agregar", ReplyAction="http://tempuri.org/IService1/AgregarResponse")]
        string Agregar(Examen_ASPNET.ServiceReference1.Solicitud reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Agregar", ReplyAction="http://tempuri.org/IService1/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(Examen_ASPNET.ServiceReference1.Solicitud reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Eliminar", ReplyAction="http://tempuri.org/IService1/EliminarResponse")]
        string Eliminar(string nsolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Eliminar", ReplyAction="http://tempuri.org/IService1/EliminarResponse")]
        System.Threading.Tasks.Task<string> EliminarAsync(string nsolicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Examen_ASPNET.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Examen_ASPNET.ServiceReference1.IService1>, Examen_ASPNET.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Examen_ASPNET.ServiceReference1.Solicitudes[] Solicitudes() {
            return base.Channel.Solicitudes();
        }
        
        public System.Threading.Tasks.Task<Examen_ASPNET.ServiceReference1.Solicitudes[]> SolicitudesAsync() {
            return base.Channel.SolicitudesAsync();
        }
        
        public Examen_ASPNET.ServiceReference1.Actividad[] Actividades() {
            return base.Channel.Actividades();
        }
        
        public System.Threading.Tasks.Task<Examen_ASPNET.ServiceReference1.Actividad[]> ActividadesAsync() {
            return base.Channel.ActividadesAsync();
        }
        
        public string Agregar(Examen_ASPNET.ServiceReference1.Solicitud reg) {
            return base.Channel.Agregar(reg);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(Examen_ASPNET.ServiceReference1.Solicitud reg) {
            return base.Channel.AgregarAsync(reg);
        }
        
        public string Eliminar(string nsolicitud) {
            return base.Channel.Eliminar(nsolicitud);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAsync(string nsolicitud) {
            return base.Channel.EliminarAsync(nsolicitud);
        }
    }
}
